test: Modify the difficulty and resource of testcases
DLTcollab/dcurl pull request #164
Opened 2019-06-06 06:29 UTC by marktwtn

Change the mwm from 9(testnet) to 14(mainnet).
Use the fixed number of threads rather than the maximum available threads,
since the testcases are for validating the function correctness,
not for exhausting the hardware resource.

2019-06-06 06:37 UTC, marktwtn commented
I do not know why the commit of @ajblane is included in this pull request.
Please do not merge it before I fix it.

2019-06-06 09:03 UTC, jserv requested changes
Ask @ajblane for final validation.

2019-06-06 11:08 UTC, marktwtn commented
I set the thread number of all the testcases to 8.

And the current commit has no problem at all.

2019-06-06 11:12 UTC, wusyong approved these changes
The reason for this request is trying to reduce the burden on CI agent. It consumes all cpu when performing the build. It will always be the lower the better IMO. Feel free to choose the proper value you feel comfortable.

2019-06-06 13:02 UTC, ajblane commented
Pass test with a broker and a AVX-accelerated remote worker with `make BUILD_REMOTE=1 BIULD_DEBUG=1 check`

2019-06-06 13:23 UTC, jserv commented
How about replacing `8` with max CPU cores?

2019-06-06 14:57 UTC, marktwtn commented
> How about replacing `8` with max CPU cores?

The original design uses (max CPU cores - 1), which makes our CI agent consume too much CPU resource.

2019-06-06 16:32 UTC, jserv commented
> The original design uses (max CPU cores - 1), which makes our CI agent consume too much CPU resource.

Alternatively, we can set its limit to `8` by adopting the available core count.

2019-06-06 17:58 UTC, marktwtn commented
> 
> 
> > The original design uses (max CPU cores - 1), which makes our CI agent consume too much CPU resource.
> 
> Alternatively, we can set its limit to `8` by adopting the available core count.

The `8` is the limit.
If the available cores are less than the limit, it will use the threads as many as the cores.
Otherwise, the limit will be used.

2019-06-06 18:16 UTC, jserv commented
> The current design uses the passed in argument as the limit.
> In our testcases, it is `8`.
> If the available cores are less than the limit, it will use the threads as many as the cores.
> Otherwise, the limit will be used.

The commit messages shall reflect the above.

2019-06-07 08:21 UTC, marktwtn commented
The comment has been updated.

2019-06-07 12:58 UTC, merged